# Generated by Django 2.2.7 on 2019-11-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartercoin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_email',
            field=models.CharField(default='addy@email.com', max_length=200),
            preserve_default=False,
        ),
    ]
