# Generated by Django 2.2.7 on 2019-11-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bartercoin', '0002_profile_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tokens_requested',
            new_name='token_balance',
        ),
    ]
